
package com.epam.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FactorialService", targetNamespace = "http://service.soap.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FactorialService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFactorial", targetNamespace = "http://service.soap.epam.com/", className = "com.epam.soap.service.GetFactorial")
    @ResponseWrapper(localName = "getFactorialResponse", targetNamespace = "http://service.soap.epam.com/", className = "com.epam.soap.service.GetFactorialResponse")
    @Action(input = "http://service.soap.epam.com/FactorialService/getFactorialRequest", output = "http://service.soap.epam.com/FactorialService/getFactorialResponse")
    public double getFactorial(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
